[build]
  command = "rm -rf public/assets/blog/example && rm posts/example.md && npm run build && npm run export"
  publish = "out/"

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
